firefly-cpp/sport-activities-features

- poetry.lock
- pyproject.toml
- sport_activities_features/tcx_manipulation.py
Replaced **python-tcxparser** with **tcxreader**, due to issues with missing values in the former.
> Dependency replacement

- README.md
- examples/weather_data_extraction.py
- poetry.lock
- pyproject.toml
- sport_activities_features/tcx_manipulation.py
- sport_activities_features/weather_identification.py
Added trackpoint timestamps to read_one_file method. Renamed tcx2 to tcx for clarity in tcx_manipulation. Added WeatherIdentification class that can be used to retrieve historical weather data of the completed trainings.
> Added Weather data.

- examples/draw_map_with_identified_hills.py
- examples/draw_map_with_identified_intervals.py
- examples/interval_data_extraction.py
- examples/read_folder.py
- sport_activities_features/interval_identification.py
- sport_activities_features/plot_data.py
- added module interval_identification, which identifies the intervals from the given input data based by power
- updated module plot_data with a new method, which draws a map with intervals
- added module interval_data_extraction, which reads a TCX file and passes the data to to the module interval_identification
- added module draw_map_with_identified_intervals, which reads a TCX file, passes the data to the module interval_identification and draws a map, where intervals are depicted
- correction of unpacking the dictionary in draw_map_with_identified_hills (line 11)
> Implementation of interval identification and small bugfix

- examples/draw_map_with_identified_intervals.py
- examples/interval_data_extraction.py
- sport_activities_features/interval_identification.py
- sport_activities_features/plot_data.py
- sport_activities_features/tcx_manipulation.py
Changes:
- intervals can now be identified by power and by heart rate (added class IntervalIdentificationByHeartrate)
- improved algorithm to identify intervals by power
- improved extraction of TCX data (reading heart rate)
- minor esthetic improvements of the map (added window title, nicer appeareance)
- various minor changes in examples (interval_data_extraction, draw_map_with_identified_intervals)
- added comments
> Improvements

- examples/read_all_files.py
- sport_activities_features/data_extraction.py
- sport_activities_features/interval_identification.py
Changes:
- added module data_extraction that writes activity data to a CSV file
- added example read_all_files that reads all TCX files in a certain folder and writes them out in a CSV file
- implementation of interval statistics
> Implementation of CSV writer

- examples/draw_map_with_identified_hills.py
- examples/draw_map_with_identified_intervals.py
- sport_activities_features/plot_data.py
Changes:
- plotting map with identified hills uses lines instead of points (fixed discontinuity of the graph)
- solved bug while unpacking the dictionary in draw_map_with_identified_hills
- solved bug while giving the input parameters to the method IntervalIdentificationByHeartrate in draw_map_with_identified_intervals
> Small improvements

- sport_activities_features/topographic_features.py
Changes:
- added method to calculate the hill gradient with the given coordinates and heights (topographic_features.py)
> Implementation of calculation of hill gradient

- examples/calculate_distance_inside_area.py
- sport_activities_features/area_identification.py
Changes:
- added module recognizing the distance inside the given area (coordinates in form of convex polygon)
- added example to represent the usage of the module
> Implementation of area recognition

- examples/calculate_distance_inside_area.py
- examples/draw_map_with_identified_intervals.py
- examples/interval_data_extraction.py
- sport_activities_features/area_identification.py
- sport_activities_features/interval_identification.py
Changes:
- standardization of documentation in various modules
> Documentation improvements

- examples/calculate_distance_inside_area.py
- sport_activities_features/area_identification.py
- area detection with rays instead of orientation of polygons (holes in areas and concave areas allowed)
> Implementation of area detection with rays

- sport_activities_features/area_identification.py
- sport_activities_features/tests/test_area_identification.py
Changes:
- test for the module area_identification is now available
- better handling of the missing heart rate data in TCX datasets
> Added test for area_identification

- examples/extract_random_activities_from_csv.py
- sport_activities_features/__init__.py
- sport_activities_features/data_extraction_from_csv.py
- data extraction from CSV file(s) to dataframe(s)
- method that returns the desired number of random activities
> data extraction from CSV file & method that returns the desired number of activities

- README.md
- sport_activities_features/tests/test_data_extraction.py
- Added test for data_extraction_from_csv
- Update README.md
> Added test & update README

- examples/extract_data_inside_area.py
- sport_activities_features/area_identification.py
Changes:
- improved area detection (severe space complexity improvement)
- improved visualization of the area detection
> Space complexity improvements

- examples/extract_data_inside_area.py
- sport_activities_features/area_identification.py
Changes:
- fixed bug in the example "extract_data_inside_area", where the activity was not plotted if no part of it was inside of an area
- added additional comments to the code
> Fixed bug at drawing the map if no points inside of an area

- examples/weather_data_extraction.py
- sport_activities_features/weather_identification.py
Added solarradiation, wind direction and dew point.
> Updated Weather identification

- README.md
- examples/dead_end_extraction.py
- examples/extract_data_inside_area.py
- sport_activities_features/dead_end_identification.py
Changes:
- added description of the modul for dead end detection
- improved README with the dead end detection visualization example
- small bugfixes (path to datasets replaced with a common name)
> Small changes in dead end detection

- sport_activities_features/gpx_manipulation.py
- sport_activities_features/missing_elevation_identification.py
- sport_activities_features/overpy_node_manipulation.py
Removed references to locally tested API and added publicly available one. Refactored Overpy Node Manipulation class so that it refers to ElevationIdentification in case of further changes.
> Overpy Node Manipulation, Elevation Identification update

- .idea/.gitignore
- .idea/inspectionProfiles/profiles_settings.xml
- .idea/misc.xml
- examples/identify_interruptions.py
- poetry.lock
- pyproject.toml
- sport_activities_features/__init__.py
- sport_activities_features/interruptions/exercise.py
- sport_activities_features/interruptions/exercise_event.py
- sport_activities_features/interruptions/interruption_processor.py
- sport_activities_features/interruptions/overpass.py
- sport_activities_features/tcx_manipulation.py
Adapted project from: Rajšp, A., & Fister, I. (2021, June). Discovering the Influence of Interruptions in Cycling Training: A Data Science Study. In International Conference on Computational Science (pp. 420-432). Springer, Cham.
> Added interruption detection

- README.md
- examples/draw_map_with_identified_hills.py
- examples/draw_map_with_identified_intervals.py
- examples/missing_elevation_data_extraction.py
- examples/overpy_node_manipulation.py
- examples/weather_data_extraction.py
- sport_activities_features/plot_data.py
Updated the PlotData and readme.md. 
Please regenerate RST readme file.
> Updated PlotData and readme

- sport_activities_features/area_identification.py
- sport_activities_features/tcx_manipulation.py
Refactored draw_map into two methods and draw_activities_inside_area_on_map into two methods so that plt object can be obtained and easily manipulated with.
> Refactored area_identification, minor bugfix in TCXFile

- sport_activities_features/dead_end_identification.py
- sport_activities_features/tcx_manipulation.py
Split show method in two parts so that plot object can be retrieved in the sub routine.
Minor print to console change in TCXFile reader.
> Dead end identification refactoring and minor change in TCXFile

- sport_activities_features/activity_generator.py
- sport_activities_features/area_identification.py
- sport_activities_features/dead_end_identification.py
Changes:
- added references to articles where existing
> Added references to several modules

- examples/draw_map_with_identified_intervals.py
- examples/extract_data_inside_area.py
- sport_activities_features/area_identification.py
- sport_activities_features/tests/test_area_identification.py
- sport_activities_features/tests/test_interval_identification.py
- sport_activities_features/weather_identification.py
Changes:
- fixed test 'test_area_identification' that was failing
- small bugfixes
> Fixed test and various bugfixes

- examples/calculate_training_load.py
- sport_activities_features/__init__.py
- sport_activities_features/training_loads.py
- tests/test_training_loads.py
Changes:
- calculation of Lucia's TRIMP
- new test case for LuciaTRIMP class
> Implementation of Lucia's TRIMP

- README.md
- docs/getting_started.rst
This pull requests append lines to README for install `python-sport-activities-features` package for Arch Linux. Fixes #90
> Add instructions for install from AUR

- examples/calculate_training_load.py
- sport_activities_features/tcx_manipulation.py
- Bug: Fixed wrong attribute parsing in altitude_max
- Improvement: Previously, if two points had the same datetime (speed calculation) was corrupted. Now one of the points with the same timestamp is ignored, so the speed calculation does not get corrupted.
> Bugfix and improvement tcx_manipulation

- sport_activities_features/classes.py
- sport_activities_features/hill_identification.py
Fixed the following: you can now select the ascent_threshold (previously fixed 30)
Added grade calculation to the hill identification algorithm
> Improvement in Hill Detection algorithm

- sport_activities_features/file_manipulation.py
- sport_activities_features/gpx_manipulation.py
- sport_activities_features/hill_identification.py
- sport_activities_features/plot_data.py
- sport_activities_features/tcx_manipulation.py
- tests/test_hill_identification.py
Created a new Superclass where common methods of TCXFile and GPXFile will be, updated plot_data (renamed Slovenian words into English variables), and added new methods for linearly (averaging out) filling missing values in lists.
Added Percents to hill grade calculation. Added basic test scenario for hill grade calculation.
> New superclass FileManipulation, update HillIdentification, PlotData added feature to fill missing values

- sport_activities_features/file_manipulation.py
- sport_activities_features/plot_data.py
- tests/test_file_manipulation.py
Added tests for missing values, changed name "tocke" to x and y
> Update file_manipulation tests, update plot_data names

- sport_activities_features/file_manipulation.py
Fixed bug where exception was thrown if the missing values were at the end of the array.
> Missing values fix

- .gitignore
- tests/data/broken1.gpx
- tests/data/broken2.gpx
- tests/data/broken3.gpx
- tests/data/broken4.gpx
- tests/data/broken5.gpx
- tests/test_gpx_file.py
Added test to verify the issue raised with #83 . The tests are passing, because the solution provided in PR #120 suceeded. Added .idea folder to gitignore and dev holder for testing prior to commiting to the repo.
> Added tests for UTF8 formatted Gpx files

- tests/test_dead_end_identification.py
- basic test for dead end identification functionality
> New test scenario for dead end identification

- examples/convert_gpx_to_csv.py
- examples/convert_tcx_to_csv.py
Added two files, hopefully helps in the ease of usage of this repo:
* convert_tcx_to_csv.py
* convert_gpx_to_csv.py
> Add examples to convert TCX/GPX file to csv

- examples/calculate_training_load.py
Example was not working before
> Update calculate_training_load.py example

- examples/calculate_training_load.py
- sport_activities_features/__init__.py
- sport_activities_features/training_loads.py
- tests/test_importing_libs.py
- tests/test_training_loads.py
Add BanisterTRIMPv2 based on reference paper, its example and test for it.
> Add BanisterTRIMPv2 based on reference paper, its example and test

- .github/workflows/test.yml
delete line due to deprecation: 'poetry config experimental.new-installer true'
> Solved workflow problem

- docs/api/activity_generator.rst
- docs/api/area_identification.rst
- docs/api/classes.rst
- docs/api/data_analysis.rst
- docs/api/data_extraction.rst
- docs/api/data_extraction_from_csv.rst
- docs/api/dead_end_identification.rst
- docs/api/file_manipulation.rst
- docs/api/gpx_manipulation.rst
- docs/api/index.rst
- docs/api/interval_identification.rst
- docs/api/missing_elevation_identification.rst
- docs/api/overpy_node_manipulation.rst
- docs/api/plot_data.rst
- docs/api/training_loads.rst
- docs/api/weather_identification.rst
- docs/conf.py
- pyproject.toml
- requirements.txt
- sport_activities_features/__init__.py
Please check if this solves the issue on readthedocs.io
> Add full API docs and latex-pdf

- .github/templates/PULL_REQUEST.md
- CONTRIBUTING.md
Summary of changes:
1. Introduced ``CONTRIBUTING.md``.
2. Updated ``.github/templates/PULL_REQUEST.md``.
> Contribution guide

- CONTRIBUTING.md
Summary of changes:
1. Updated versions of dependencies in ``CONTRIBUTING.md``.
> Version of dependencies

- README.md
Add TCXReader.jl to related frameworks
> Update README.md: Add TCXReader.jl to related frameworks

- README.md
- sport_activities_features/__init__.py
- sport_activities_features/missing_elevation_identification.py
- tests/test_missing_elevation_identification.py
Added OpenTopoData support in MissingElevationIdentification cases. Now another API is supported. Also added tests for it and updated readme.
> OpenTopoData support in ElevationIdentification

- sport_activities_features/missing_elevation_identification.py
- tests/test_missing_elevation_identification.py
Modified the test to reflect changes in the API response format. Tests should pass now.
> Fixed tests (elevation)
